export { default as Footer } from './footer/footer';
export { default as MeetTeam } from './meetTeam/meetTeam';
export { default as Faq } from './faq/faq';
export { default as Services } from './services/services';
export { default as About } from './about/about';
export { default as Contact } from './contact/contact';
export { default as Banner } from './banner/banner';
export { default as ColorPicker } from './colorPicker/colorPicker';
export { default as NavLinks } from './navLinks/navLinks';